In [13]:
import numpy as np
import matplotlib as plt

In [16]:
l=["1",2,3,4]
print(np.array(l, dtype=np.int64))

[1 2 3 4]


In [17]:
l1=[[1,2,3],[1,2,3]]
print(np.array(l1))

[[1 2 3]
 [1 2 3]]


In [20]:
import pandas as pd
d={
    "a":[1,2,3],
    "p":[1,2,3]
}
print(pd.DataFrame(d)) # here list size of values must be same

   a  p
0  1  1
1  2  2
2  3  3
